{% set version = "0.25" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tinytex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tinytex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tinytex/tinytex_{{ version }}.tar.gz
  sha256: ead3d70e6b3dab3f6942e9797b902f9a5b76ee396429dffd4ab24d2a7bff707d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-xfun >=0.5
  run:
    - r-base
    - r-xfun >=0.5

test:
  commands:
    - $R -e "library('tinytex')"           # [not win]
    - "\"%R%\" -e \"library('tinytex')\""  # [win]

about:
  home: https://github.com/yihui/tinytex
  license: MIT
  summary: Helper functions to install and maintain the 'LaTeX' distribution named 'TinyTeX' (<https://yihui.name/tinytex/>), a lightweight, cross-platform, portable, and easy-to-maintain version of 'TeX Live'. This package also contains helper functions to compile 'LaTeX' documents, and install missing 'LaTeX' packages
    automatically.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ConorIA

# Package: tinytex
# Type: Package
# Title: Helper Functions to Install and Maintain 'TeX Live', and Compile 'LaTeX' Documents
# Version: 0.16
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre", "cph"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person(family = "RStudio, Inc.", role = "cph"), person("Fernando", "Cagua", role = "ctb"), person("Ethan", "Heinzen", role = "ctb"), person() )
# Description: Helper functions to install and maintain the 'LaTeX' distribution named 'TinyTeX' (<https://yihui.name/tinytex/>), a lightweight, cross-platform, portable, and easy-to-maintain version of 'TeX Live'. This package also contains helper functions to compile 'LaTeX' documents, and install missing 'LaTeX' packages automatically.
# Imports: xfun (>= 0.5)
# Suggests: testit, rstudioapi
# License: MIT + file LICENSE
# URL: https://github.com/yihui/tinytex
# BugReports: https://github.com/yihui/tinytex/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-17 04:27:50 UTC; yihui
# Author: Yihui Xie [aut, cre, cph] (<https://orcid.org/0000-0003-0645-5666>), RStudio, Inc. [cph], Fernando Cagua [ctb], Ethan Heinzen [ctb]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2019-09-17 05:10:02 UTC
